### ISSUE TITLE
Missing addresses in IPv4 and IPv6

### ISSUE THREAD

**Issue by Naouak** [DylanPiercey/is-local-ip#1]
According to wikipedia article on private network ( https://en.wikipedia.org/wiki/Private_network ), there is a missing range for IPv4 and IPv6:

 - 169.254.1.0 -> 169.254.254.255
 - fd00::/8

Is it possible to add them?

**Comment by DylanPiercey** [comment]
Thanks for your help on this. I cleaned it up a tad and released as 1.1.0
